version: "3.3"
services:

  backend:
    env_file:
      - .env.local
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  redis:
    image: redis

  redis-insights:
    image: redislabs/redisinsight
    ports:
      - "8001:8001"
